<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Allotments.aspx.cs" Inherits="FRASS.WebUI.Parcels.Allotments" %>
<%@ MasterType VirtualPath="~/Site.master" %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
	<script type="text/javascript" language="javascript">
		function requestStart(sender, args) {
			if (args.get_eventTarget().indexOf("DownloadPDF") > 0) {
				args.set_enableAjax(false);
			}
		}
	</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<div style="padding-bottom: 5px;">
		<asp:Button ID="Button_ExportDBF" Text="Export to PDF" runat="server" OnClick="Button_ExportPDF_Click"/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<asp:DropDownList ID="DropDownList_MarketModels" runat="server" Visible="false"></asp:DropDownList>
		<asp:DropDownList ID="DropDownList_RPA" runat="server"></asp:DropDownList>
		<asp:Button ID="Button_ApplyMarketModel" runat="server" Text="Apply Market Model with RPA Portfolio" OnClick="Button_ApplyMarketModel_Click"  Visible="false"/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<asp:DropDownList ID="DropDownList_StumpageModels" runat="server" Visible="false"></asp:DropDownList>
		<asp:Button ID="Button_ApplyStumpageModels" runat="server" Text="Apply Stumpage Model" OnClick="Button_ApplyStumpageModel_Click"  Visible="false"/>
	</div>
	<telerik:RadGrid ID="RadGrid1" GridLines="None" AutoGenerateColumns="false" PageSize="50"
		AllowPaging="false" AllowSorting="false" runat="server"
		AllowFilteringByColumn="false"
		ShowStatusBar="false"
		OnNeedDataSource="RadGrid1_NeedDataSource"
		OnItemDataBound="RadGrid1_ItemDataBound"
		>
		<PagerStyle Position="TopAndBottom" />
		<MasterTableView ShowFooter="false" CommandItemDisplay="None">
			<Columns>
				<telerik:GridTemplateColumn>
					<HeaderTemplate>
						Allotment Value Allocation<br />Based on BIA Data Circa 1999
					</HeaderTemplate>
					<ItemTemplate>
						<table cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
							<colgroup>
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
							</colgroup>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Generated By</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_User" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Date Generated</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><%=System.DateTime.Now.ToShortDateString() %></td>
							</tr>
							<tr>
								<td style="font-weight: bold;">Parcel Number</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_ParcelNum" runat="server"></asp:Label></td>
								<td style="font-weight: bold;">Acres</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;" colspan="3"><asp:Label ID="Label_Acres" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Township</td>
								<td style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_Township" runat="server"></asp:Label></td>
								<td colspan="4" rowspan="2" style="background-color: #DDD9C3; border-top: 1px solid #000000; border-bottom: 1px solid #DDD9C3; text-align: center;">
									<asp:Label ID="Label_Owner" runat="server" Font-Bold="true"></asp:Label>
								</td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Range</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;">
									<asp:Label ID="Label_Range" runat="server"></asp:Label>
								</td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Section</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_Section" runat="server"></asp:Label></td>
								<td colspan="4" style="border-top: 1px dashed #000000;">&nbsp;</td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">County</td>
								<td style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_County" runat="server"></asp:Label></td>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Legal Description</td>
								<td colspan="3" style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_LegalDesc" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="2" style="border-top: 1px dashed #000000; font-weight: bold;">County Assessor Land Value</td>
								<td colspan="4" style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;">
									<asp:Label ID="Label_CountyAssessorLandValue" runat="server"></asp:Label>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="border-bottom: 1px solid #000000; border-top: 1px dashed #000000; font-weight: bold;">County Assessor Building Value</td>
								<td colspan="4" style="border-bottom: 1px solid #000000; border-top: 1px solid #000000; background-color: #DDD9C3; "><asp:Label ID="Label_CountyAssessorBuildingValue" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-top: 1px solid #000000; text-align: center;" colspan="6">Harvest Volumes & Value Summary</td>
							</tr>
							<tr>
								<td colspan="6">
									<table cellspacing="0" cellpadding="0" style="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-collapse: collapse;">
										<colgroup>
											<col width="78px"/>
											<col width="78px"/>
											<col width="78px" />
											<col width="78px"/>
											<col width="78px"/>
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
										</colgroup>
										<tr style="background-color: #eeeeee;">
											<td colspan="2" style="border-right: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: center;">Stand Info</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Current Rotation</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Next Rotation</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Third Rotation Into Perpetuity</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Total Present Value</td>
										</tr>
										<tr style="background-color: #eeeeee;">
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;">Stand ID Number</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Operable Commercial Timber Land Acres</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Harvest Year</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Net Present Value</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Rotation Length (years)</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Net Present Value</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Rotation Length</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Soil Expectation Value (Present Value)</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Stand</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Per Acre</td>
										</tr>
										<asp:Repeater ID="Repeater_HarvestData" runat="server" OnItemDataBound="Repeater_HarvestData_ItemDataBound">
											<ItemTemplate>
												<tr>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandID" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_Acres" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_HarvestYear" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_NPV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_RotationLength_R2" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_NPV_R2" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_RotationLength_SEV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_SEV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandValue" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandValue_PerAcre" runat="server"></asp:Label></td>
												</tr>
											</ItemTemplate>
										</asp:Repeater>
										<tr>
											<td rowspan="2" colspan="2" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: center; vertical-align: bottom;">New Road Construction</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Scheduled In</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Current Cost</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Future Cost</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: normal; text-align: center;">Discounted Road Cost</td>
										</tr>
										<tr>
										<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadSchedule" runat="server"></asp:Label></td>
											<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadCurrentCost" runat="server"></asp:Label></td>
											<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadFuture" runat="server"></asp:Label></td>
											<td style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadDiscountCost" runat="server"></asp:Label></td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-weight: normal; text-align: right;">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; font-weight: bold; text-align: right;">Total Value based on Operable Commercial Timber Land Acres:</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalCommercialAcres" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValue" runat="server">&nbsp;</asp:Label></td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3; border-right: 1px solid #000000;"><asp:Label ID="Label_TotalValueAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Value per Acre (Forested Acres):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalAcresForested" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000;">&nbsp;</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValueForestedPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Value per Acre (Entire Parcel):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalAcresEntireParcel" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000;">&nbsp;</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalalueEntireParcelPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Bare Land Value (Entire Parcel):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalBareLand" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_BareLandValue" runat="server">&nbsp;</asp:Label></td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValuePareLandPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="6">
									<table cellpadding="0" cellspacing="0" width="100%">
										<tr>
											<td style="font-weight: bold; text-align: center;" colspan="7">Allottee Owner Names and Shares (1999)</td>
										</tr>
										<tr style="background-color: #eeeeee; border-top: 1px solid #000000;">
											<td style="font-weight: bold; text-align: center;">Last Name</td>
											<td style="font-weight: bold; text-align: center;">First Name</td>
											<td style="font-weight: bold; text-align: center;">Allottee Number</td>
											<td style="font-weight: bold; text-align: center;">Undivided Interest Share</td>
											<td style="font-weight: bold; text-align: center;">Prorated Value</td>
											<td style="font-weight: bold; text-align: center;">Fractionation Scalar</td>
											<td style="font-weight: bold; text-align: center;">Value Adjusted for Fractionation</td>
										</tr>
										<asp:Repeater ID="Repeater_Allottees" runat="server" OnItemDataBound="Repeater_Allottees_ItemDataBound">
											<ItemTemplate>
												<tr>
													<td style="text-align: right; border-bottom: 1px dashed #000000;">
														<asp:Label ID="Label_LastName" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; border-bottom: 1px dashed #000000;">
														<asp:Label ID="Label_FirstName" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; border-bottom: 1px dashed #000000;">
														<asp:Label ID="Label_AllotteeNumber" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; background-color: #DDD9C3;">
														<asp:Label ID="Label_UndivdedInteresetShare" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; background-color: #DDD9C3;">
														<asp:Label ID="Label_ProratedValue" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; background-color: #DDD9C3;">
														<asp:Label ID="Label_FractionationScalar" runat="server"></asp:Label>
													</td>
													<td style="text-align: right; background-color: #DDD9C3;">
														<asp:Label ID="Label_ValueAdjustedForFractionation" runat="server"></asp:Label>
													</td>
												</tr>
											</ItemTemplate>
										</asp:Repeater>
									</table>
								</td>
							</tr>
						</table>
					</ItemTemplate>
				</telerik:GridTemplateColumn>
			</Columns>
		</MasterTableView>
	</telerik:RadGrid>
	<asp:Panel ID="Panel_Errors" runat="server">
		<asp:Label ID="Label_ErrorMessage" ForeColor="Red" Font-Bold="true" runat="server"></asp:Label>
	</asp:Panel>
</asp:Content>
