<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Report.aspx.cs" Inherits="FRASS.Parcels.Report" %>
<%@ MasterType VirtualPath="~/Site.master" %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
	<script type="text/javascript" language="javascript">
		function requestStart(sender, args) {
			if (args.get_eventTarget().indexOf("DownloadPDF") > 0) {
				args.set_enableAjax(false);
			}

		}
		$(document).ready(function () {
			$(".group1").colorbox({ rel: 'group1', transition: "fade", maxWidth: "800px", maxHeight: "600px"});
		});
	</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<div style="padding-bottom: 5px;">
		<asp:Button ID="Button_ExportDBF" Text="Export to PDF" runat="server" OnClick="Button_ExportPDF_Click"/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<asp:DropDownList ID="DropDownList_MarketModels" runat="server" Visible="false"></asp:DropDownList>
		<asp:DropDownList ID="DropDownList_RPA" runat="server" Visible="false"></asp:DropDownList>
		<asp:Button ID="Button_ApplyMarketModel" runat="server" Text="Apply Market Model with RPA Portfolio" OnClick="Button_ApplyMarketModel_Click"  Visible="false"/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<asp:DropDownList ID="DropDownList_StumpageModels" runat="server" Visible="false"></asp:DropDownList>
		<asp:Button ID="Button_ApplyStumpageModels" runat="server" Text="Apply Stumpage Model" OnClick="Button_ApplyStumpageModels_Click"  Visible="false"/>
	</div>
	<telerik:RadGrid ID="RadGrid1" GridLines="None" AutoGenerateColumns="false" PageSize="50"
		AllowPaging="false" AllowSorting="false" runat="server"
		AllowFilteringByColumn="false"
		ShowStatusBar="false"
		OnNeedDataSource="RadGrid1_NeedDataSource"
		OnItemDataBound="RadGrid1_ItemDataBound"
		>
		<PagerStyle Position="TopAndBottom" />
		<MasterTableView ShowFooter="false" DataKeyNames="ParcelID" CommandItemDisplay="None">
			<Columns>
				<telerik:GridTemplateColumn HeaderText="Forest Resource Analysis System Software Reporting System">
					<ItemTemplate>
						<table cellspacing="0" cellpadding="0">
							<colgroup>
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
							</colgroup>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Generated By</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_User" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Date Generated</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><%=System.DateTime.Now.ToShortDateString() %></td>
							</tr>
							<tr>
								<td style="font-weight: bold;">Parcel Number</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_ParcelNum" runat="server"></asp:Label></td>
								<td style="font-weight: bold;">Acres</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;" colspan="3"><asp:Label ID="Label_Acres" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Township</td>
								<td style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_Township" runat="server"></asp:Label></td>
								<td colspan="4" rowspan="2" style="background-color: #DDD9C3; border-top: 1px solid #000000; border-bottom: 1px solid #DDD9C3; text-align: center;">
									<asp:Label ID="Label_Owner" runat="server" Font-Bold="true"></asp:Label>
								</td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Range</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_Range" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Section</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_Section" runat="server"></asp:Label></td>
								<td colspan="4" style="border-top: 1px dashed #000000;">&nbsp;</td>
							</tr>
							<tr>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">County</td>
								<td style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_County" runat="server"></asp:Label></td>
								<td style="border-top: 1px dashed #000000; font-weight: bold;">Legal Description</td>
								<td colspan="3" style="border-top: 1px solid #000000; background-color: #DDD9C3; border-bottom: 1px solid #DDD9C3;"><asp:Label ID="Label_LegalDesc" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="6" style="border-top: 1px solid #000000; font-weight: bold; text-align: center;">Soils Derived Data on Parcel</td>
							</tr>
							<tr>
								<td style="border-top: 1px solid #000000; background-color: #FFFFFF; border-bottom: 1px solid #DDD9C3;">
									MUKEY
								</td>
								<td style="border-top: 1px solid #000000; background-color: #FFFFFF; border-bottom: 1px solid #DDD9C3;">
									MUSYM
								</td>
								<td style="border-top: 1px solid #000000; background-color: #FFFFFF; border-bottom: 1px solid #DDD9C3;">
									Acres
								</td>
								<td colspan="3" style="border-top: 1px solid #000000; background-color: #FFFFFF; border-bottom: 1px solid #DDD9C3;">
									<a href="/Documents/Map Unit Description.pdf" target="_blank" style="color: Blue; font-weight: bold;">Description</a>
								</td>
							</tr>
							<asp:Repeater ID="Repeater_DerivedDataOnParcel" runat="server" OnItemDataBound="Repeater_DerivedDataOnParcelItemDataBound">
								<ItemTemplate>
									<tr>
										<td style="border-top: 1px dashed #000000; background-color: #DDD9C3; border-bottom: 1px dashed #DDD9C3;">
											<asp:Label ID="Label_MUKey" runat="server"></asp:Label>
										</td>
										<td style="border-top: 1px dashed #000000; background-color: #DDD9C3; border-bottom: 1px dashed #DDD9C3;">
											<asp:Label ID="Label_MUSYM" runat="server"></asp:Label>
										</td>
										<td style="border-top: 1px dashed #000000; background-color: #DDD9C3; border-bottom: 1px dashed #DDD9C3;">
											<asp:Label ID="Label_MUKeyAcres" runat="server"></asp:Label>
										</td>
										<td colspan="3" style="border-top: 1px dashed #000000; background-color: #DDD9C3; border-bottom: 1px dashed #DDD9C3;">
											<asp:Label ID="Label_MUKeyDescription" runat="server"></asp:Label>
										</td>
									</tr>	
								</ItemTemplate>
							</asp:Repeater>
							<tr>
								<td colspan="6" style="border-top: 1px solid #000000; border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">MUKEY (Soil Survey)</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">MUKEY<br />MUSYM</td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SoilSurveyMUKEY" runat="server" OnItemDataBound="Repeater_SoilSurveyMUKEY_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border-bottom: solid 1px #DDD9C3;">
														<asp:Label ID="Label_MUKEY" runat="server" Font-Bold="true"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000; background-color: #DDD9C3;">Acres</td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SoilSurveyAcres" runat="server" OnItemDataBound="Repeater_SoilSurveyAcres_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Acres" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Fire Damage Susceptibility.pdf" target="_blank" style="color: blue;">Fire Damage Susceptibility</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_FireDamageSusceptibility" runat="server" OnItemDataBound="Repeater_FireDamageSusceptibility_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_FireDamageSusceptibility" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Potential for Damage by Fire.pdf" target="_blank" style="color: blue;">Potential for Damage by Fire</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_FireDamagePotential" runat="server" OnItemDataBound="Repeater_FireDamagePotential_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_FireDamagePotential" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Soil Rutting Hazard.pdf" target="_blank" style="color: blue;">Soil Rutting Hazard</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SoilRuttingHazard" runat="server" OnItemDataBound="Repeater_SoilRuttingHazard_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SoilRuttingHazard" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Suitability for Roads (Natural Surface) (WA).pdf" target="_blank" style="color: blue;">Suitability for Roads (Natural Surface) (WA)</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SuitabilityForRoadsNaturalSurface" runat="server" OnItemDataBound="Repeater_SuitabilityForRoadsNaturalSurface_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SuitabilityForRoadsNaturalSurface" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Suitability for Log Landings (WA).pdf" target="_blank" style="color: blue;">Suitability for Log Landings (WA)</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SuitabilityForLogLandings" runat="server" OnItemDataBound="Repeater_SuitabilityForLogLandings_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SuitabilityForLogLandings" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Construction Limitations for Haul Roads and Log Landings.pdf" target="_blank" style="color: blue;">Construction Limitations for Haul Roads and Log Landings</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_Construction" runat="server" OnItemDataBound="Repeater_Construction_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Construction" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Harvest Equipment Operability.pdf" target="_blank" style="color: blue;">Harvest Equipment Operability</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_Harvest" runat="server" OnItemDataBound="Repeater_Harvest_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Harvest" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Mechanical Site Preparation (Surface).pdf" target="_blank" style="color: blue;">Mechanical Site Preparation (Surface)</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SitePrepSurface" runat="server" OnItemDataBound="Repeater_SitePrepSurface_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Surface" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Mechanical Site Preparation (Deep).pdf" target="_blank" style="color: blue;">Mechanical Site Preparation (Deep)</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SitePrepDeep" runat="server" OnItemDataBound="Repeater_SitePrepDeep_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Deep" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Suitability for Hand Planting.pdf" target="_blank" style="color: blue;">Suitability for Hand Planting</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_Hand" runat="server" OnItemDataBound="Repeater_Hand_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Hand" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Suitability for Mechanical Planting.pdf" target="_blank" style="color: blue;">Suitability for Mechanical Planting</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_Mech" runat="server" OnItemDataBound="Repeater_Mech_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_Mech" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;"><a href="/Documents/Potential for Seedling Mortality.pdf" target="_blank" style="color: blue;">Potential for Seedling Mortality</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SeedlingMortality" runat="server" OnItemDataBound="Repeater_SeedlingMortality_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SeedlingMortality" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold;"><a href="/Documents/Site Index PSME.pdf" target="_blank" style="color: blue;">Tree Site Index Douglas-fir</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SIDougFir" runat="server" OnItemDataBound="Repeater_SIDougFir_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SI" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold;"><a href="/Documents/Site Index ALRU.pdf" target="_blank" style="color: blue;">Tree Site Index Western Red Alder</a></td>
								<td colspan="4" style="background-color: #DDD9C3; border-bottom: solid 1px #DDD9C3;">
									<table border="0" cellpadding="0" cellspacing="0">
										<tr>
											<asp:Repeater ID="Repeater_SIWesternRedAlder" runat="server" OnItemDataBound="Repeater_SIWesternRedAlder_ItemDataBound">
												<ItemTemplate>
													<td width="100px" style="border: solid 1px #DDD9C3;">
														<asp:Label ID="Label_SI" runat="server"></asp:Label>
													</td>
												</ItemTemplate>
											</asp:Repeater>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="6" style="border-top: 1px solid #000000; border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Threatened, Endangered & Sensitive Species Habitat</td>
							</tr>
							<tr>
								<td colspan="4" style="font-weight: bold; border-bottom: 1px dashed #000000;">Species</td>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px solid #ffffff; background-color: #DDD9C3;">Acres</td>
							</tr>
							<tr>
								<td colspan="4" style="font-weight: bold; border-bottom: 1px dashed #000000;">Marbled Murrelet, (<em>Brachyramphus marmoratus</em>)</td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #ffffff; background-color: #DDD9C3;"><asp:Label ID="Label_MarbledMurrelet" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="4" style="font-weight: bold; border-bottom: 1px dashed #000000;">Northern Spotted Owl, (<em>Strix occidentalis caurina</em>)</td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #ffffff; background-color: #DDD9C3;"><asp:Label ID="Label_NorthernSpotedOwl" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="4" style="font-weight: bold; border-bottom: 1px dashed #000000;">American Bald Eagle, (<em>Haliaeetus leucocephalus</em>)</td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #ffffff; background-color: #DDD9C3;"><asp:Label ID="Label_Eagle" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Physical Site Characteristics</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">&nbsp;</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Min</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Max</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Mean</td>
								<td style="font-weight: bold; border-bottom: 1px dashed #000000;">&nbsp;</td>
							</tr>	
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Elevation (feet)</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MinElevationFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MaxElevationFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MeanElevationFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px dashed #000000;">&nbsp;</td>
							</tr>	
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px solid #000000;">Slope (degrees)</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MinSlope" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MaxSlope" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MeanSlope" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="font-weight: bold; text-align: center;">&nbsp;</td>
							</tr>	
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Existing Roads on Parcel</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Road Type</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Meters</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Feet</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Miles</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Surface Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthFeets" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Main Haul Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Paved State Highways:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="font-weight: bold; text-align: center;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Distance of Travel to Reach Paved Haul Road</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Road Type</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Meters</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Feet</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Miles</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Nearest Road is</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">If Parcel has no road, then straight-line distance to nearest road is (Construction Required):</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_NearRoadUse" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Travel distance along Surface Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Travel distance along Main Haul Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="font-weight: bold; text-align: center;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="border-top: 1px dashed #000000; font-weight: bold; text-align: center;">Timber Stand Statistics (current)</td>
							</tr>
							<tr>
								<td colspan="6">
									<table border="0" cellpadding="0" cellspacing="0" width="100%">
										<tr>
											<td width="12%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Stand ID Number</td>
											<td width="12%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Vegetation Label</td>
											<td width="12%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Site Index</td>
											<td width="13%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Riparian Zone Acres</td>
											<td width="13%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Operable Commercial Timber Land Acres</td>
											<td width="13%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">BF/Acre per Stand</td>
											<td width="12%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Total Forested Acres on Parcel</td>
											<td width="12%" style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Total Operable Volume</td>
										</tr>
										<asp:Repeater ID="Repeater_TimberStandStatistics" runat="server" OnItemDataBound="Repeater_TimberStandStatisticsItemDataBound">
											<ItemTemplate>
												<tr>
													<td style="border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_StandID" runat="server"></asp:Label></td>
													<td style="border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_VegLabel" runat="server"></asp:Label></td>
													<td style="border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_SI" runat="server"></asp:Label></td>
													<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_AcresNotOperable" runat="server"></asp:Label></td>
													<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_AcresOperable" runat="server"></asp:Label></td>
													<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_BFAcrePerStand" runat="server"></asp:Label></td>
													<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_TotalAcres" runat="server"></asp:Label></td>
													<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;"><asp:Label ID="Label_TotalBFOnStand" runat="server"></asp:Label></td>
												</tr>
											</ItemTemplate>
										</asp:Repeater>
										<tr>
											<td width="12%" style="border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;">Totals:</td>
											<td width="12%" style="border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;">&nbsp;</td>
											<td width="12%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;">&nbsp;</td>
											<td width="13%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;"><asp:Label ID="Label_TotalRiparianAcres" runat="server"></asp:Label></td>
											<td width="13%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;"><asp:Label ID="Label_TotalOperableAcres" runat="server"></asp:Label></td>
											<td width="12%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;">&nbsp;</td>
											<td width="12%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;"><asp:Label ID="Label_TotalAcresOnParcel" runat="server"></asp:Label></td>
											<td width="12%" style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;"><asp:Label ID="Label_TotalBF" runat="server"></asp:Label></td>
										</tr>
									</table>
								</td>
							</tr>

							<tr>
								<td colspan="6" style="border-top: 1px dashed #000000; font-weight: bold; text-align: center;">Current Parcel Timber Summary (Operable Acres Only)</td>
							</tr>
							<tr>
								<td colspan="2" style="border-top: 1px dashed #000000; font-weight: bold;">&nbsp;</td>
								<td style="text-align: center; border-top: 1px dashed #000000; font-weight: bold;">Total BF</td>
								<td colspan="3" style="border-top: 1px dashed #000000; font-weight: bold;">&nbsp;</td>
							</tr>

							<asp:Repeater ID="Repeater_CurrentParcelTimberSummary" runat="server" OnItemDataBound="Repeater_CurrentParcelTimberSummary_ItemDataBound">
								<ItemTemplate>
									<tr>
										<td colspan="2" style="border-top: 1px dashed #000000;  font-weight: bold;"><asp:Label ID="Label_Species" runat="server"></asp:Label></td>
										<td style="text-align: right; border-top: 1px dashed #000000; border-bottom: 1px solid #DDD9C3; background-color: #DDD9C3;">
											<asp:Label ID="Label_TotalBF" runat="server"></asp:Label>
										</td>
										<td colspan="3" style="border-top: 1px dashed #000000; font-weight: bold;">&nbsp;</td>
									</tr>
								</ItemTemplate>
							</asp:Repeater>
							<tr>
								<td colspan="2" style="border-top: 1px dashed #000000; font-weight: bold;">Totals</td>
								<td style="text-align: right; border-top: 1px dashed #000000; font-weight: bold; background-color: #DDD9C3;"><asp:Label ID="Label_TotalBFCurrentParcel" runat="server"></asp:Label></td>
								<td colspan="3" style="border-top: 1px dashed #000000; font-weight: bold;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="border-top: 1px dashed #000000; font-weight: bold; text-align: center;">Supporting Imagery</td>
							</tr>
							<asp:Repeater ID="Repeater_Imagery" runat="server" OnItemDataBound="Repeater_Imagery_ItemBound">
								<ItemTemplate>
									<tr>
										<td colspan="6" style="border-top: 1px dashed #000000; font-weight: bold;">
											<asp:Literal ID="Literal_Map" runat="server"></asp:Literal>
										</td>
									</tr>
								</ItemTemplate>
							</asp:Repeater>
						</table>
					</ItemTemplate>
				</telerik:GridTemplateColumn>
			</Columns>
		</MasterTableView>
	</telerik:RadGrid>
</asp:Content>