<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master"  AutoEventWireup="true" CodeBehind="StumpageValueReport.aspx.cs" Inherits="FRASS.Parcels.StumpageValueReport" %>
<%@ MasterType VirtualPath="~/Site.master" %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
	<script type="text/javascript" language="javascript">
		function requestStart(sender, args) {
			if (args.get_eventTarget().indexOf("DownloadPDF") > 0) {
				args.set_enableAjax(false);
			}

		}
	</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
		<div style="padding-bottom: 5px;">
			<asp:Button ID="Button_ExportDBF" Text="Export to PDF" runat="server" OnClick="Button_ExportPDF_Click"/>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<asp:DropDownList ID="DropDownList_MarketModels" runat="server" Visible="false"></asp:DropDownList>
			<asp:Button ID="Button_ApplyMarketModel" runat="server" Text="Apply Market Model" OnClick="Button_ApplyMarketModel_Click"  Visible="false"/>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<asp:DropDownList ID="DropDownList_StumpageModels" runat="server" Visible="false"></asp:DropDownList>
			<asp:Button ID="Button_ApplyStumpageModels" runat="server" Text="Apply Stumpage Model" OnClick="Button_ApplyStumpageModel_Click"  Visible="false"/>
		</div>
			<telerik:RadGrid ID="RadGrid1" GridLines="None" AutoGenerateColumns="false" PageSize="50"
				AllowPaging="false" AllowSorting="false" runat="server"
				AllowFilteringByColumn="false"
				ShowStatusBar="false"
				OnNeedDataSource="RadGrid1_NeedDataSource"
				OnItemDataBound="RadGrid1_ItemDataBound"
				>
		<PagerStyle Position="TopAndBottom" />
		<MasterTableView ShowFooter="false" DataKeyNames="ParcelID" CommandItemDisplay="None">
			<Columns>
				<telerik:GridTemplateColumn HeaderText="Forest Resource Analysis System Software Reporting System" UniqueName="Col1">
					<ItemTemplate>
						<table cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
							<colgroup>
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
								<col width="130px"/>
								<col width="130px"/>
								<col width="130px" />
							</colgroup>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Generated By</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_User" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Date Generated</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><%=System.DateTime.Now.ToShortDateString() %></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Parcel Number:</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;"><asp:Label ID="Label_ParcelNumber" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Acres</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;"><asp:Label ID="Label_Acres" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Hectares</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;"><asp:Label ID="Label_Hectares" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000; text-align: right;"><asp:Image ID="Image_AcreActionSize" runat="server" /></td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="5"><asp:Label ID="Label_AcreActions" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Owner Category</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_OwnerCategory" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Allotment Number</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_AllotmentNumber" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Township:</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="5"><asp:Label ID="Label_Township" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Range</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="5"><asp:Label ID="Label_Range" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Section</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="5"><asp:Label ID="Label_Section" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">County</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_County" runat="server"></asp:Label></td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Legal Description</td>
								<td style="background-color: #DDD9C3; border-bottom: 1px solid #000000;" colspan="2"><asp:Label ID="Label_LegalDescription" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td style="font-weight: bold; border-bottom: 1px solid #000000; text-align: center;" colspan="6">Zoning</td>
							</tr>
							<asp:Repeater ID="Repeater_Zoning" runat="server" OnItemDataBound="Repeater_ZoningItemDataBound">
								<ItemTemplate>
									<tr>
										<td style="border-bottom: 1px solid #000000; font-weight: bold; text-align: right; padding-right: 5px;">
											<asp:Label ID="Label_Zoning" runat="server"></asp:Label>
										</td>
										<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">
											<asp:Label ID="Label_ZoningAcres" runat="server"></asp:Label> Acres
										</td>
										<td style="border-bottom: 1px solid #000000; text-align: right; "><asp:Image ID="Image_Zoning" runat="server" /></td>
										<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;" colspan="3"><asp:Label ID="Label_ZoningAction" runat="server" /></td>
									</tr>	
								</ItemTemplate>
							</asp:Repeater>
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Threatened, Endangered & Sensitive Species Habitat</td>
							</tr>
							<tr>
								<td colspan="3" style="font-weight: bold; border-bottom: 1px solid #000000;">Northern Spotted Owl, (<em>Strix occidentalis caurina</em>)</td>
								<td style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #ffffff; text-align: right;"><asp:Image ID="Image_NorthernSpotedOwl" runat="server"></asp:Image></td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_NorthernSpotedOwl" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="3" style="font-weight: bold; border-bottom: 1px solid #000000;">Marbled Murrelet, (<em>Brachyramphus marmoratus</em>)</td>
								<td style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #ffffff; text-align: right;"><asp:Image ID="Image_MarbledMurrelet" runat="server"></asp:Image></td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MarbledMurrelet" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="3" style="font-weight: bold; border-bottom: 1px solid #000000;">American Bald Eagle, (<em>Haliaeetus leucocephalus</em>)</td>
								<td style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #ffffff; text-align: right;"><asp:Image ID="Image_Eagle" runat="server"></asp:Image></td>
								<td colspan="2" style="font-weight: normal; border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_Eagle" runat="server"></asp:Label></td>
							</tr>	
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Existing Roads on Parcel</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Road Type</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Meters</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Feet</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Miles</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Surface Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthFeets" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingSurfaceLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Main Haul Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingMainHaulLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Paved Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthMeters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthFeet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ExistingPavedLengthMiles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="font-weight: bold; text-align: center;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">Distance of Travel to Reach Paved Haul Road</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Road Type</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Meters</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Feet</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Miles</td>
								<td style="font-weight: bold; border-bottom: 1px solid #000000;">Nearest Road is</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">If Parcel has no road, then straight-line distance to nearest road is (Construction Required):</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_DistToNearest_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_NearRoadUse" runat="server"></asp:Label></td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Travel distance along Surface Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_ToSurface_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" style="font-weight: bold; border-bottom: 1px dashed #000000;">Travel distance along Main Haul Roads:</td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Meters" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Feet" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_MainHaul_Miles" runat="server"></asp:Label></td>
								<td style="border-bottom: 1px solid #000000; background-color: #DDD9C3;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" style="font-weight: bold; text-align: center;">Harvest Volumes & Value Summary</td>
							</tr>
							<tr>
								<td colspan="6" >
									<table cellspacing="0" cellpadding="0" style="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-collapse: collapse;">
										<colgroup>
											<col width="78px"/>
											<col width="78px"/>
											<col width="78px" />
											<col width="78px"/>
											<col width="78px"/>
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
											<col width="78px" />
										</colgroup>
										<tr>
											<td colspan="2" style="border-right: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: center;">Stand Info</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Current Rotation</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Next Rotation</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Third Rotation Into Perpetuity</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: bold; text-align: center;">Total Present Value</td>
										</tr>
										<tr>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;">Stand ID Number</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Operable Commercial Timber Land Acres</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Harvest Year</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Net Present Value</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Rotation Length (years)</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Net Present Value</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Rotation Length</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Soil Expectation Value (Present Value)</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Stand</td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Per Acre</td>
										</tr>
										<asp:Repeater ID="Repeater_HarvestData" runat="server" OnItemDataBound="Repeater_HarvestData_ItemDataBound">
											<ItemTemplate>
												<tr>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandID" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_Acres" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_HarvestYear" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_NPV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_RotationLength_R2" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_NPV_R2" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_RotationLength_SEV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_SEV" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandValue" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: right; background-color: #DDD9C3;"><asp:Label ID="Label_StandValue_PerAcre" runat="server"></asp:Label></td>
												</tr>
											</ItemTemplate>
										</asp:Repeater>
										<tr>
											<td rowspan="2" colspan="2" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: center; vertical-align: bottom;">New Road Construction</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Scheduled In</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Current Cost</td>
											<td colspan="2" style="font-weight: normal; text-align: center;">Future Cost</td>
											<td colspan="2" style="border-right: 1px solid #000000; font-weight: normal; text-align: center;">Discounted Road Cost</td>
										</tr>
										<tr>
										<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadSchedule" runat="server"></asp:Label></td>
											<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadCurrentCost" runat="server"></asp:Label></td>
											<td colspan="2" style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadFuture" runat="server"></asp:Label></td>
											<td style="border-bottom: 1px solid #000000; font-weight: normal; text-align: right;"><asp:Label ID="Label_RoadDiscountCost" runat="server"></asp:Label></td>
											<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-weight: normal; text-align: right;">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; font-weight: bold; text-align: right;">Total Value based on Operable Commercial Timber Land Acres:</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalCommercialAcres" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValue" runat="server">&nbsp;</asp:Label></td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3; border-right: 1px solid #000000;"><asp:Label ID="Label_TotalValueAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Value per Acre (Forested Acres):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalAcresForested" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000;">&nbsp;</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValueForestedPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Value per Acre (Entire Parcel):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalAcresEntireParcel" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000;">&nbsp;</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalalueEntireParcelPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="7" style="border-bottom: 1px solid #000000; border-left: 1px solid #000000; font-weight: bold; text-align: right;">Bare Land Value (Entire Parcel):</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; "><asp:Label ID="Label_TotalBareLand" runat="server">&nbsp;</asp:Label> Acres</td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_BareLandValue" runat="server">&nbsp;</asp:Label></td>
											<td style="font-weight: normal; text-align: right; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; background-color: #DDD9C3;"><asp:Label ID="Label_TotalValuePareLandPerAcre" runat="server">&nbsp;</asp:Label>/Acre</td>
										</tr>
										<tr>
											<td colspan="10" style="font-weight: bold; text-align: right;"><asp:Button ID="Button_ViewAllotments" runat="server" Text="View Allotment Allocation Report" OnClick="Button_ViewAllotments_Click" /></td>
										</tr>
										<tr>
											<td colspan="10" style="font-weight: bold; text-align: center; border-bottom: 1px solid #000000;">Harvest Reports<br /><em>Based on Operable Commercial Timber Land Acres<br />Values Represent Future Values</em></td>										
										</tr>
										<asp:Repeater ID="Repeater_HarvestReport" runat="server" OnItemDataBound="Repeater_HarvestReport_ItemDataBound">
											<ItemTemplate>
												<tr>
													<td colspan="10" style="background-color: #EEEEEE; font-weight: bold; text-align: left; border-right: 1px solid #000000; border-left: 1px solid #000000; border-bottom: 1px solid #000000;">Stand ID Number: <asp:Label ID="Label_HarvestReportStandIDNumber" runat="server"></asp:Label></td>
												</tr>
												<tr>
													<td colspan="3" style="background-color: #EEEEEE; border-right: 1px solid #000000; border-left: 1px solid #000000; border-bottom: 1px solid #000000; font-weight: bold; text-align: center;">&nbsp;</td>
													<td colspan="3" style="background-color: #EEEEEE; border-right: 1px solid #000000; font-weight: bold; text-align: center; border-bottom: 1px solid #000000;">Current Rotation</td>
													<td colspan="2" style="background-color: #EEEEEE; border-right: 1px solid #000000; font-weight: bold; text-align: center; border-bottom: 1px solid #000000;">Next Rotation</td>
													<td colspan="2" style="background-color: #EEEEEE; border-right: 1px solid #000000; font-weight: bold; text-align: center; border-bottom: 1px solid #000000;">Third Rotation Into Perpetuity</td>
												</tr>
												<tr>
													<td colspan="3" style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;">Species & Quality Code</td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;">Volume at Harvest</td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Value/MBF in <asp:Label ID="Label_Year1" runat="server"></asp:Label></td>
													<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Quality Code Value in <asp:Label ID="Label_Year2" runat="server"></asp:Label></td>
													<td colspan="2" style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;">Volume at Harvest (<asp:Label ID="Label_Year3" runat="server"></asp:Label>)</td>
													<td colspan="2" style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;">Volume at First Entry (<asp:Label ID="Label_Year5" runat="server"></asp:Label>)</td>
												</tr>
												<asp:Repeater ID="Repeater_HarvestReport_Species" runat="server" OnItemDataBound="Repeater_HarvestReport_Species_ItemDataBound">
													<ItemTemplate>
														<tr>
															<td colspan="10" style="background-color: #DDD9C3; font-weight: bold; text-align: left; border-right: 1px solid #000000; border-left: 1px solid #000000; border-bottom: 1px solid #000000;"><asp:Label ID="Label_LogReportSpecies" runat="server"></asp:Label></td>
														</tr>
														<asp:Repeater ID="Repeater_HarvestReport_Sorts" runat="server" OnItemDataBound="Repeater_HarvestReport_Sorts_ItemDataBound">
															<ItemTemplate>
																<tr>
																	<td colspan="3" style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;"><asp:Label ID="Label_Sort" runat="server"></asp:Label></td>
																	<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; border-left: 1px solid #000000; text-align: center;"><asp:Label ID="Label_Volume_R1" runat="server"></asp:Label></td>
																	<td style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;"><asp:Label ID="Label_ValuePerMBF_R1" runat="server"></asp:Label></td>
																	<td style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;"><asp:Label ID="Label_SortValue_R1" runat="server"></asp:Label></td>
																	<td colspan="2" style="border-bottom: 1px solid #000000; border-right: 1px dashed #000000; text-align: center;"><asp:Label ID="Label_Volume_R2" runat="server"></asp:Label></td>
																	<td colspan="2" style="border-bottom: 1px solid #000000; border-right: 1px solid #000000; text-align: center;"><asp:Label ID="Label_Volume_R3" runat="server"></asp:Label></td>
																</tr>
															</ItemTemplate>
														</asp:Repeater>
													</ItemTemplate>
												</asp:Repeater>
												<tr>
													<td colspan="10" style="border-bottom: 1px solid #000000; background-color: #ffffff; font-weight: bold; text-align: left; ">&nbsp;</td>
												</tr>
											</ItemTemplate>
										</asp:Repeater>
									</table>
								</td>
							</tr>
						</table>
					</ItemTemplate>
				</telerik:GridTemplateColumn>
			</Columns>
		</MasterTableView>
	</telerik:RadGrid>
</asp:Content>
