using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Aspose.Pdf.Generator;
using FRASS.Reports;
using FRASS.DAL;
using System.Text.RegularExpressions;

namespace FRASS.Reports.ReportSection
{
	internal class ParcelInfo
	{
		private ReportUtilities ReportUtilities;
		private Table InfoTable;
		private User User;
		private Parcel Parcel;
		private bool ShowTopBorder;
		private bool ShowCountyValues;
		public ParcelInfo(Table table, User user, Parcel parcel)
			: this(table, user, parcel, true, true) { }

		public ParcelInfo(Table table, User user, Parcel parcel, bool showTopBorder, bool showCountyValues)
		{
			ReportUtilities = new ReportUtilities();
			InfoTable = ReportUtilities.AppendNewSixColumnTable(table);
			User = user;
			Parcel = parcel;
			ShowTopBorder = showTopBorder;
			ShowCountyValues = showCountyValues;
			if (showTopBorder)
			{
				var gi = new GraphInfo();
				gi.LineWidth = .5f;
				gi.Color = new Color(128, 128, 128);
				InfoTable.Border = new BorderInfo();
				InfoTable.Border.Top = gi;
				InfoTable.Border.Bottom = gi;
			}
		}

		public void SetParcelInfoRows()
		{
			SetGeneratedByRow();
			SetParcelNumberRow();
			SetTownshipAndOwnerRow();
			SetRangeRow(1);
			SetSectionRow(1);
			SetCountyRow();
			if (ShowCountyValues)
			{
				SetCountyLandValueRow();
				SetCountyBuildingValueRow();
			}
		}
		public void SetParcelInfoRowsForValueReport(string baseFilePath)
		{
			SetGeneratedByRow();
			SetParcelNumberRow();
			SetImageRow(baseFilePath);
			SetTownshipRow();
			SetRangeRow(6);
			SetSectionRow(6);
			SetCountyRow();
		}

		private void SetGeneratedByRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Generated By", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, User.FirstName + " " + User.LastName, AlignmentType.Left);
			ReportUtilities.AddLabelCell(row, "Date Generated", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, DateTime.Now.ToShortDateString(), AlignmentType.Left, 3);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}
		private void SetParcelNumberRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Parcel Number", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelNumber, AlignmentType.Left);
			ReportUtilities.AddLabelCell(row, "Acres", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.Acres.ToString("N1"), AlignmentType.Left,3);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}
		private void SetImageRow(string baseFilePath)
		{
			var filePath = "";
			var txt = "";
			if (Parcel.Acres < 10M)
			{
				txt = "This parcel appears to be below the size needed to represent a commercial timber production parcel and may not be considered a viable Highest and Best Use for timber production.";
				filePath = baseFilePath + "/images/32_stop.png";
			}
			else if (Parcel.Acres < 20M)
			{
				txt = "This parcel may be marginal in size needed to represent a commercial timber production parcel. Caution should be applied in reference to timber production costs for this parcel.";
				filePath = baseFilePath + "/images/32_warn.png";
			}
			else
			{
				txt = "This parcel appears to meet the size requirements for a valid commercial timber production parcel.";
				filePath = baseFilePath + "/images/32_ok.png";
			}
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddImageCell(row, filePath, AlignmentType.Right, ImageFileType.Png);
			ReportUtilities.AddHighlightCell(row, txt, AlignmentType.Left, 5);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}
		
		private void SetCountyRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "County", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelCounties.Select(uu => uu.County.County1).Distinct().ToList<string>(), AlignmentType.Left);
			ReportUtilities.AddLabelCell(row, "Legal Description", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, GetLegals(), AlignmentType.Left, 3);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}
		private void SetCountyLandValueRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "County Assessor Land Value", AlignmentType.Left, 2);
			ReportUtilities.AddHighlightCell(row, GetLandValue(), AlignmentType.Left, 4);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}
		private void SetCountyBuildingValueRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "County Assessor Building Value", AlignmentType.Left, 2);
			ReportUtilities.AddHighlightCell(row, GetBuildingValue(), AlignmentType.Left, 4);
		}

		private List<string> GetOwnerCategories()
		{
			var ots = Parcel.ParcelAllotments.Select(uu => uu.OwnerType.OwnerType1).Distinct().OrderBy(uu => uu);
			return ots.ToList<string>();
		}
		private List<string> GetAllotmentNumbers()
		{
			var ans = Parcel.ParcelAllotments.Select(uu => uu.AllotmentNumber).Distinct().OrderBy(uu => uu);
			return ans.ToList<string>();
		}

		private void SetTownshipAndOwnerRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Township", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelAllotments.Select(uu => uu.Town).Distinct().ToList<string>(), AlignmentType.Left);
			var cell = ReportUtilities.AddHighlightCellBold(row, GetOwnerNames(), AlignmentType.Center, 4);
			cell.RowSpan = 3;
			cell.Border = ReportUtilities.RowBottomBorderInfo;
		}
		private List<string> GetOwnerNames()
		{
			var list = new List<string>();
			var ots = Parcel.ParcelAllotments.Select(uu => uu.OwnerType.OwnerType1);

			var owner = new List<string>();
			foreach (var parcelOwner in Parcel.ParcelOwners.Select(uu => uu.Owner).Distinct())
			{
				list.Add(parcelOwner.Name);
				var address = Regex.Split(parcelOwner.Address, "<br />");
				foreach (var line in address)
				{
					if (!string.IsNullOrWhiteSpace(line))
					{
						list.Add(line);
					}
				}
				
				var str = "";
				if (parcelOwner.State != null)
				{
					str = str + parcelOwner.City.Trim() + ", " + parcelOwner.State.StateInitial.Trim() + " " + parcelOwner.Zip.Trim();
				}
				else
				{
					str = str + parcelOwner.City.Trim() + ", " + parcelOwner.Zip.Trim();
				}
				if (parcelOwner.Zip4.Trim() != string.Empty)
				{
					str = str + "-" + parcelOwner.Zip4.Trim();
				}
				list.Add(str);
			}
			var ct = 0;
			foreach (var str in owner.OrderBy(uu => uu).Distinct())
			{
				list.Add(str);
				ct = ct + 1;
			}
			return list;
		}
		private void SetRangeRow(int colSpan)
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Range", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelAllotments.Select(uu => uu.Range).Distinct().ToList<string>(), AlignmentType.Left, colSpan);
			if (colSpan == 6)
			{
				row.Border = ReportUtilities.RowBottomBorderInfo;
			}
		}
		private void SetSectionRow(int colSpan)
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Section", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelAllotments.Select(uu => uu.Section).Distinct().ToList<string>(), AlignmentType.Left, colSpan);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}

		private void SetTownshipRow()
		{
			var row = InfoTable.Rows.Add();
			ReportUtilities.AddLabelCell(row, "Township", AlignmentType.Left);
			ReportUtilities.AddHighlightCell(row, Parcel.ParcelAllotments.Select(uu => uu.Town).Distinct().ToList<string>(), AlignmentType.Left, 6);
			row.Border = ReportUtilities.RowBottomBorderInfo;
		}

		private List<string> GetLegals()
		{
			var list = new List<string>();
			var ots = Parcel.ParcelAllotments.Select(uu => uu.OwnerType.OwnerType1);
			if (ots.Where(uu => uu == "AiT" || uu == "T" || uu == "Q").FirstOrDefault() != null)
			{

				foreach (var pa in Parcel.ParcelAllotments)
				{
					foreach (var pal in pa.ParcelAllotmentLegals)
					{
						list.Add(pal.Legal.Replace("<br/>", ""));
					}

				}
			}
			else
			{
				foreach (var pl in Parcel.ParcelLegals.OrderBy(uu => uu.Legal))
				{
					list.Add(pl.Legal.Replace("<br/>", ""));
				}
			}
			return list;
		}
		private string GetLandValue()
		{
			return "$" + Parcel.ParcelLegals.Sum(uu => uu.LandValue);
		}
		private string GetBuildingValue()
		{
			return "$" + Parcel.ParcelLegals.Sum(uu => uu.BuildingValue);
		}
	}
}