//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRASS.Services.Proxies.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GenerateFullParcelReportDeliveredMarketModel", ReplyAction="http://tempuri.org/IReportService/GenerateFullParcelReportDeliveredMarketModelRes" +
            "ponse")]
        void GenerateFullParcelReportDeliveredMarketModel(int UserID, int ParcelID, int PortfolioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GenerateFullParcelReportStumpageMarketModel", ReplyAction="http://tempuri.org/IReportService/GenerateFullParcelReportStumpageMarketModelResp" +
            "onse")]
        void GenerateFullParcelReportStumpageMarketModel(int UserID, int ParcelID, int PortfolioID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : FRASS.Services.Proxies.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<FRASS.Services.Proxies.ReportService.IReportService>, FRASS.Services.Proxies.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateFullParcelReportDeliveredMarketModel(int UserID, int ParcelID, int PortfolioID) {
            base.Channel.GenerateFullParcelReportDeliveredMarketModel(UserID, ParcelID, PortfolioID);
        }
        
        public void GenerateFullParcelReportStumpageMarketModel(int UserID, int ParcelID, int PortfolioID) {
            base.Channel.GenerateFullParcelReportStumpageMarketModel(UserID, ParcelID, PortfolioID);
        }
    }
}
