//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRASS
{
    public partial class Error
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.WebControls.Label Label_ErrorMessage;
        protected global::System.Web.UI.WebControls.HyperLink HyperLink_Back;
    }
}
