<?xml version="1.0" encoding="utf-8"?><Database Name="FRASS" EntityNamespace="FRASS.DAL" ContextNamespace="FRASS.DAL.Context" Class="FRASSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KAMIAK_2K8;Initial Catalog=FRASS;Persist Security Info=True;User ID=sa" SettingsObjectName="FRASS.DAL.Properties.Settings" SettingsPropertyName="FRASSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_HistoricLogPrices" Member="v_HistoricLogPrices">
    <Type Name="v_HistoricLogPrice">
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketSpeciesAbbreviations" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SMPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Saw2Price" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Saw3Price" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Saw4Price" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Saw4CNPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="PulpPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="CamprunPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Export12Price" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Export8Price" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="ChipPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Counties" Member="Counties">
    <Type Name="County">
      <Column Name="CountyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="County" Member="County1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="County_ParcelCounty" Member="ParcelCounties" ThisKey="CountyID" OtherKey="CountyID" Type="ParcelCounty" />
    </Type>
  </Table>
  <Table Name="dbo.UserTypes" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserType" Member="UserType1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserType_User" Member="Users" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricLogPrices" Member="HistoricLogPrices">
    <Type Name="HistoricLogPrice">
      <Column Name="HistoricLogPriceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_HistoricLogPrice" Member="LogMarketReportSpecy" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpecy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogMarketReportSpecies" Member="LogMarketReportSpecies">
    <Type Name="LogMarketReportSpecy">
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogMarketSpecies" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketSpeciesAbbreviations" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_HistoricLogPrice" Member="HistoricLogPrices" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="HistoricLogPrice" />
      <Association Name="LogMarketReportSpecy_LogMarketReportSpeciesMarket" Member="LogMarketReportSpeciesMarkets" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpeciesMarket" />
      <Association Name="LogMarketReportSpecy_LogMarketReportSpeciesSpecy" Member="LogMarketReportSpeciesSpecies" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpeciesSpecy" />
      <Association Name="LogMarketReportSpecy_MarketModelPortfolioDeliveredLogModelDetail" Member="MarketModelPortfolioDeliveredLogModelDetails" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="MarketModelPortfolioDeliveredLogModelDetail" />
      <Association Name="LogMarketReportSpecy_RPAPortfolioDetail" Member="RPAPortfolioDetails" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="RPAPortfolioDetail" />
      <Association Name="Specy_LogMarketReportSpecy" Member="Specy" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="Specy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogMarketReportSpeciesMarkets" Member="LogMarketReportSpeciesMarkets">
    <Type Name="LogMarketReportSpeciesMarket">
      <Column Name="LogMarketReportSpeciesMarketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_LogMarketReportSpeciesMarket" Member="LogMarketReportSpecy" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpecy" IsForeignKey="true" />
      <Association Name="TimberMarket_LogMarketReportSpeciesMarket" Member="TimberMarket" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="TimberMarket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogMarketReportSpeciesSpecies" Member="LogMarketReportSpeciesSpecies">
    <Type Name="LogMarketReportSpeciesSpecy">
      <Column Name="LogMarketReportSpeciesSpeciesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_LogMarketReportSpeciesSpecy" Member="LogMarketReportSpecy" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpecy" IsForeignKey="true" />
      <Association Name="Specy_LogMarketReportSpeciesSpecy" Member="Specy" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="Specy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelData" Member="MarketModelDatas">
    <Type Name="MarketModelData">
      <Column Name="MarketModelDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarketModelTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeriesID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(6,1) NOT NULL" CanBeNull="false" />
      <Association Name="MarketModelType_MarketModelData" Member="MarketModelType" ThisKey="MarketModelTypeID" OtherKey="MarketModelTypeID" Type="MarketModelType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelPortfolioCosts" Member="MarketModelPortfolioCosts">
    <Type Name="MarketModelPortfolioCost">
      <Column Name="MarketModelPortfolioCostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarketModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReforestationCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessFeeRock" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="AccessFeeTimber" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaintenanceFeeRockHaul" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaintenanceFeeTimberHaul" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="RoadConstructionCosts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioCost" Member="MarketModelPortfolio" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelPortfolioDeliveredLogModelDetails" Member="MarketModelPortfolioDeliveredLogModelDetails">
    <Type Name="MarketModelPortfolioDeliveredLogModelDetail">
      <Column Name="MarketModelPortfolioDeliveredLogModelDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarketModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveredLogPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoggingCosts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HaulingCosts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverheadAndAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentNetValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfitAndRisk" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_MarketModelPortfolioDeliveredLogModelDetail" Member="LogMarketReportSpecy" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpecy" IsForeignKey="true" />
      <Association Name="TimberMarket_MarketModelPortfolioDeliveredLogModelDetail" Member="TimberMarket" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="TimberMarket" IsForeignKey="true" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioDeliveredLogModelDetail" Member="MarketModelPortfolio" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelPortfolioInflationDetails" Member="MarketModelPortfolioInflationDetails">
    <Type Name="MarketModelPortfolioInflationDetail">
      <Column Name="MarketModelPortfolioInflationDetailsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarketModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginningYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LandownerDiscountRate" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Column Name="InflationRate" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioInflationDetail" Member="MarketModelPortfolio" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelTypes" Member="MarketModelTypes">
    <Type Name="MarketModelType">
      <Column Name="MarketModelTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MarketModelType" Member="MarketModelType1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MarketModelType_MarketModelData" Member="MarketModelDatas" ThisKey="MarketModelTypeID" OtherKey="MarketModelTypeID" Type="MarketModelData" />
    </Type>
  </Table>
  <Table Name="dbo.Owners" Member="Owners">
    <Type Name="Owner">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Zip4" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Association Name="Owner_ParcelOwner" Member="ParcelOwners" ThisKey="OwnerID" OtherKey="OwnerID" Type="ParcelOwner" />
      <Association Name="State_Owner" Member="State" ThisKey="StateID" OtherKey="StateID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerTypes" Member="OwnerTypes">
    <Type Name="OwnerType">
      <Column Name="OwnerTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OwnerType" Member="OwnerType1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OwerDesc" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="OwnerType_ParcelAllotment" Member="ParcelAllotments" ThisKey="OwnerTypeID" OtherKey="OwnerTypeID" Type="ParcelAllotment" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelAllotmentLegals" Member="ParcelAllotmentLegals">
    <Type Name="ParcelAllotmentLegal">
      <Column Name="ParcelAllotmentLegalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelAllotmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Legal" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="ParcelAllotment_ParcelAllotmentLegal" Member="ParcelAllotment" ThisKey="ParcelAllotmentID" OtherKey="ParcelAllotmentID" Type="ParcelAllotment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelAllotments" Member="ParcelAllotments">
    <Type Name="ParcelAllotment">
      <Column Name="ParcelAllotmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllotmentNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Town" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Range" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Section" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ParcelAllotment_ParcelAllotmentLegal" Member="ParcelAllotmentLegals" ThisKey="ParcelAllotmentID" OtherKey="ParcelAllotmentID" Type="ParcelAllotmentLegal" />
      <Association Name="ParcelAllotment_ParcelAllotmentShare" Member="ParcelAllotmentShares" ThisKey="ParcelAllotmentID" OtherKey="ParcelAllotmentID" Type="ParcelAllotmentShare" />
      <Association Name="OwnerType_ParcelAllotment" Member="OwnerType" ThisKey="OwnerTypeID" OtherKey="OwnerTypeID" Type="OwnerType" IsForeignKey="true" />
      <Association Name="Parcel_ParcelAllotment" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelAllotmentShares" Member="ParcelAllotmentShares">
    <Type Name="ParcelAllotmentShare">
      <Column Name="ParcelAllotmentShareID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelAllotmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelAllotteeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Share" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="ParcelAllotment_ParcelAllotmentShare" Member="ParcelAllotment" ThisKey="ParcelAllotmentID" OtherKey="ParcelAllotmentID" Type="ParcelAllotment" IsForeignKey="true" />
      <Association Name="ParcelAllottee_ParcelAllotmentShare" Member="ParcelAllottee" ThisKey="ParcelAllotteeID" OtherKey="ParcelAllotteeID" Type="ParcelAllottee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelAllottees" Member="ParcelAllottees">
    <Type Name="ParcelAllottee">
      <Column Name="ParcelAllotteeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AllotteeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ParcelAllottee_ParcelAllotmentShare" Member="ParcelAllotmentShares" ThisKey="ParcelAllotteeID" OtherKey="ParcelAllotteeID" Type="ParcelAllotmentShare" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelCounties" Member="ParcelCounties">
    <Type Name="ParcelCounty">
      <Column Name="ParcelCountyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="County_ParcelCounty" Member="County" ThisKey="CountyID" OtherKey="CountyID" Type="County" IsForeignKey="true" />
      <Association Name="Parcel_ParcelCounty" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelEagles" Member="ParcelEagles">
    <Type Name="ParcelEagle">
      <Column Name="ParcelEagleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nest_Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelEagle" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelHaulZones" Member="ParcelHaulZones">
    <Type Name="ParcelHaulZone">
      <Column Name="ParcelHaulZoneID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HaulZoneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelHaulZone" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelLegal" Member="ParcelLegals">
    <Type Name="ParcelLegal">
      <Column Name="ParcelLegalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LandValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuildingValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Legal" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelLegal" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelMurreletts" Member="ParcelMurreletts">
    <Type Name="ParcelMurrelett">
      <Column Name="ParcelMurrelettID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MM_Suita" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelMurrelett" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelOwls" Member="ParcelOwls">
    <Type Name="ParcelOwl">
      <Column Name="ParcelOwlID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Association Name="Parcel_ParcelOwl" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelOwners" Member="ParcelOwners">
    <Type Name="ParcelOwner">
      <Column Name="ParcelOwnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Owner_ParcelOwner" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
      <Association Name="Parcel_ParcelOwner" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelRoadDistances" Member="ParcelRoadDistances">
    <Type Name="ParcelRoadDistance">
      <Column Name="ParcelRoadDistanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToMainHaul" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="MainHaulToPaved" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="DistanceToNearestFromParcelBoundary" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="NearRoadUseFromParcelBoundary" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Parcel_ParcelRoadDistance" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelRoadUseLengths" Member="ParcelRoadUseLengths">
    <Type Name="ParcelRoadUseLength">
      <Column Name="ParcelRoadUseLengthID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PavedLength" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="MainHaulLength" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="SurfaceLength" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Association Name="Parcel_ParcelRoadUseLength" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelStats" Member="ParcelStats">
    <Type Name="ParcelStat">
      <Column Name="ParcelStatID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMinFt" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMaxFt" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMeanFt" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMinM" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMaxM" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="ElevationMeanM" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="SlopeMin" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="SlopeMax" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="SlopeMean" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelStat" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelZonings" Member="ParcelZonings">
    <Type Name="ParcelZoning">
      <Column Name="ParcelZoningID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelZoningTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="ParcelZoningType_ParcelZoning" Member="ParcelZoningType" ThisKey="ParcelZoningTypeID" OtherKey="ParcelZoningTypeID" Type="ParcelZoningType" IsForeignKey="true" />
      <Association Name="Parcel_ParcelZoning" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelZoningTypes" Member="ParcelZoningTypes">
    <Type Name="ParcelZoningType">
      <Column Name="ParcelZoningTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Zoning" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ParcelZoningType_ParcelZoning" Member="ParcelZonings" ThisKey="ParcelZoningTypeID" OtherKey="ParcelZoningTypeID" Type="ParcelZoning" />
    </Type>
  </Table>
  <Table Name="dbo.SiteSettings" Member="SiteSettings">
    <Type Name="SiteSetting">
      <Column Name="SiteSettingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Setting" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Species" Member="Species">
    <Type Name="Specy">
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CommonName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbreviation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Latin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LatinAbbreviation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Taxa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Specy_LogMarketReportSpecy" Member="LogMarketReportSpecies" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="LogMarketReportSpecy" />
      <Association Name="Specy_LogMarketReportSpeciesSpecy" Member="LogMarketReportSpeciesSpecies" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="LogMarketReportSpeciesSpecy" />
      <Association Name="Specy_StumpageGroupSpecy" Member="StumpageGroupSpecies" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="StumpageGroupSpecy" />
      <Association Name="Specy_StumpagePrice" Member="StumpagePrices" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="StumpagePrice" />
      <Association Name="Specy_TimberGrade" Member="TimberGrades" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="TimberGrade" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateInitial" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="State_Owner" Member="Owners" ThisKey="StateID" OtherKey="StateID" Type="Owner" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageGroupQualityCodes" Member="StumpageGroupQualityCodes">
    <Type Name="StumpageGroupQualityCode">
      <Column Name="StumpageGroupQualityCodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QualityCodeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioRPAData" Member="StumpageModelPortfolioRPADatas" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageModelPortfolioRPAData" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioValue" Member="StumpageModelPortfolioValues" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageModelPortfolioValue" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioMultiplier" Member="StumpageModelPortfolioMultipliers" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageModelPortfolioMultiplier" />
      <Association Name="StumpageGroup_StumpageGroupQualityCode" Member="StumpageGroup" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageGroups" Member="StumpageGroups">
    <Type Name="StumpageGroup">
      <Column Name="StumpageGroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StumpageGroupName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StumpageGroup_StumpageGroupQualityCode" Member="StumpageGroupQualityCodes" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroupQualityCode" />
      <Association Name="StumpageGroup_StumpageGroupSpecy" Member="StumpageGroupSpecies" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroupSpecy" />
      <Association Name="StumpageGroup_StumpageModelPortfolioRPAData" Member="StumpageModelPortfolioRPADatas" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageModelPortfolioRPAData" />
      <Association Name="StumpageGroup_StumpageModelPortfolioValue" Member="StumpageModelPortfolioValues" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageModelPortfolioValue" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageGroupSpecies" Member="StumpageGroupSpecies">
    <Type Name="StumpageGroupSpecy">
      <Column Name="StumpageGroupSpeciesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Specy_StumpageGroupSpecy" Member="Specy" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="Specy" IsForeignKey="true" />
      <Association Name="StumpageGroup_StumpageGroupSpecy" Member="StumpageGroup" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioCosts" Member="StumpageModelPortfolioCosts">
    <Type Name="StumpageModelPortfolioCost">
      <Column Name="StumpageModelPortfolioCostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReforestationCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessFeeRock" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="AccessFeeTimber" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaintenanceFeeRockHaul" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaintenanceFeeTimberHaul" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="RoadConstructionCosts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioCost" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioInflationDetails" Member="StumpageModelPortfolioInflationDetails">
    <Type Name="StumpageModelPortfolioInflationDetail">
      <Column Name="StumpageModelPortfolioInflationDetailsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginningYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LandownerDiscountRate" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Column Name="InflationRate" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioInflationDetail" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioRPAData" Member="StumpageModelPortfolioRPADatas">
    <Type Name="StumpageModelPortfolioRPAData">
      <Column Name="StumpageModelPortfolioRPADataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginningReport" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndingReport" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StumpageGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StumpageGroupQualityCodeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Haul3" Type="System.Decimal" DbType="Decimal(6,5)" CanBeNull="true" />
      <Column Name="Haul4" Type="System.Decimal" DbType="Decimal(6,5)" CanBeNull="true" />
      <Column Name="Haul5" Type="System.Decimal" DbType="Decimal(6,5)" CanBeNull="true" />
      <Column Name="Longevity" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioRPAData" Member="StumpageGroupQualityCode" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageGroupQualityCode" IsForeignKey="true" />
      <Association Name="StumpageGroup_StumpageModelPortfolioRPAData" Member="StumpageGroup" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroup" IsForeignKey="true" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioRPAData" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolios" Member="StumpageModelPortfolios">
    <Type Name="StumpageModelPortfolio">
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortfolioName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioCost" Member="StumpageModelPortfolioCosts" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolioCost" Cardinality="One" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioInflationDetail" Member="StumpageModelPortfolioInflationDetails" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolioInflationDetail" Cardinality="One" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioRPAData" Member="StumpageModelPortfolioRPADatas" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolioRPAData" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioShare" Member="StumpageModelPortfolioShares" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolioShare" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioValue" Member="StumpageModelPortfolioValues" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolioValue" />
      <Association Name="StumpageModelPortfolio_Report" Member="Reports" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="Report" />
      <Association Name="User_StumpageModelPortfolio" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioShares" Member="StumpageModelPortfolioShares">
    <Type Name="StumpageModelPortfolioShare">
      <Column Name="StumpageModelPortfolioShareID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioShare" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
      <Association Name="User_StumpageModelPortfolioShare" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioValues" Member="StumpageModelPortfolioValues">
    <Type Name="StumpageModelPortfolioValue">
      <Column Name="StumpageModelPortfolioValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StumpageGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StumpageGroupQualityCodeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Haul3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Haul4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Haul5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="OverheadAndAdmin" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Haul3CurrentNetValue" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Haul4CurrentNetValue" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Haul5CurrentNetValue" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="ProfitAndRisk" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioValue" Member="StumpageGroupQualityCode" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageGroupQualityCode" IsForeignKey="true" />
      <Association Name="StumpageGroup_StumpageModelPortfolioValue" Member="StumpageGroup" ThisKey="StumpageGroupID" OtherKey="StumpageGroupID" Type="StumpageGroup" IsForeignKey="true" />
      <Association Name="StumpageModelPortfolio_StumpageModelPortfolioValue" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StumpagePrices" Member="StumpagePrices">
    <Type Name="StumpagePrice">
      <Column Name="StumpagePricesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarketDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimberQualityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HaulingZone1" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="HaulingZone2" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="HaulingZone3" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="HaulingZone4" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="HaulingZone5" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Specy_StumpagePrice" Member="Specy" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="Specy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimberCurrentStands" Member="TimberCurrentStands">
    <Type Name="TimberCurrentStand">
      <Column Name="TimberCurrentStandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Yield_Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Veg_Label" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TimberCurrentStand_TimberCurrentStandSort" Member="TimberCurrentStandSorts" ThisKey="TimberCurrentStandID" OtherKey="TimberCurrentStandID" Type="TimberCurrentStandSort" />
      <Association Name="TimberCurrentStand_ParcelRiparian" Member="ParcelRiparians" ThisKey="STD_ID" OtherKey="STD_ID" Type="ParcelRiparian" />
    </Type>
  </Table>
  <Table Name="dbo.TimberCurrentStandSorts" Member="TimberCurrentStandSorts">
    <Type Name="TimberCurrentStandSort">
      <Column Name="TimberCurrentStandSortID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimberCurrentStandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberGradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Board_SN" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PctBrd" Type="System.Decimal" DbType="Decimal(10,9) NOT NULL" CanBeNull="false" />
      <Association Name="TimberCurrentStand_TimberCurrentStandSort" Member="TimberCurrentStand" ThisKey="TimberCurrentStandID" OtherKey="TimberCurrentStandID" Type="TimberCurrentStand" IsForeignKey="true" />
      <Association Name="TimberGrade_TimberCurrentStandSort" Member="TimberGrade" ThisKey="TimberGradeID" OtherKey="TimberGradeID" Type="TimberGrade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimberFutureStands" Member="TimberFutureStands">
    <Type Name="TimberFutureStand">
      <Column Name="TimberFutureStandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Yield_Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportYears" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TimberFutureStand_TimberFutureStandSort" Member="TimberFutureStandSorts" ThisKey="TimberFutureStandID" OtherKey="TimberFutureStandID" Type="TimberFutureStandSort" />
    </Type>
  </Table>
  <Table Name="dbo.TimberFutureStandSorts" Member="TimberFutureStandSorts">
    <Type Name="TimberFutureStandSort">
      <Column Name="TimberFutureStandSortID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimberFutureStandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberGradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Board_SN" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PctBrd" Type="System.Decimal" DbType="Decimal(10,9) NOT NULL" CanBeNull="false" />
      <Association Name="TimberFutureStand_TimberFutureStandSort" Member="TimberFutureStand" ThisKey="TimberFutureStandID" OtherKey="TimberFutureStandID" Type="TimberFutureStand" IsForeignKey="true" />
      <Association Name="TimberGrade_TimberFutureStandSort" Member="TimberGrade" ThisKey="TimberGradeID" OtherKey="TimberGradeID" Type="TimberGrade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimberGrades" Member="TimberGrades">
    <Type Name="TimberGrade">
      <Column Name="TimberGradeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TimberGrade_TimberCurrentStandSort" Member="TimberCurrentStandSorts" ThisKey="TimberGradeID" OtherKey="TimberGradeID" Type="TimberCurrentStandSort" />
      <Association Name="TimberGrade_TimberFutureStandSort" Member="TimberFutureStandSorts" ThisKey="TimberGradeID" OtherKey="TimberGradeID" Type="TimberFutureStandSort" />
      <Association Name="Specy_TimberGrade" Member="Specy" ThisKey="SpeciesID" OtherKey="SpeciesID" Type="Specy" IsForeignKey="true" />
      <Association Name="TimberMarket_TimberGrade" Member="TimberMarket" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="TimberMarket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimberMarkets" Member="TimberMarkets">
    <Type Name="TimberMarket">
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Market" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TimberMarket_LogMarketReportSpeciesMarket" Member="LogMarketReportSpeciesMarkets" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="LogMarketReportSpeciesMarket" />
      <Association Name="TimberMarket_MarketModelPortfolioDeliveredLogModelDetail" Member="MarketModelPortfolioDeliveredLogModelDetails" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="MarketModelPortfolioDeliveredLogModelDetail" />
      <Association Name="TimberMarket_TimberGrade" Member="TimberGrades" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="TimberGrade" />
      <Association Name="TimberMarket_RPAPortfolioDetail" Member="RPAPortfolioDetails" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="RPAPortfolioDetail" />
    </Type>
  </Table>
  <Table Name="dbo.UserStatuses" Member="UserStatuses">
    <Type Name="UserStatuse">
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserStatuse_User" Member="Users" ThisKey="UserStatusID" OtherKey="UserStatusID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.TRS_IndexNumbers" Member="TRS_IndexNumbers">
    <Type Name="TRS_IndexNumber">
      <Column Name="IndexNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Township" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Range" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Section" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Reports" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarketModelPortfolioID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StumpageModelPortfolioID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReportTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PDF" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="StumpageModelPortfolio_Report" Member="StumpageModelPortfolio" ThisKey="StumpageModelPortfolioID" OtherKey="StumpageModelPortfolioID" Type="StumpageModelPortfolio" IsForeignKey="true" />
      <Association Name="ReportType_Report" Member="ReportType" ThisKey="ReportTypeID" OtherKey="ReportTypeID" Type="ReportType" IsForeignKey="true" />
      <Association Name="User_Report" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Parcel_Report" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
      <Association Name="MarketModelPortfolio_Report" Member="MarketModelPortfolio" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportTypes" Member="ReportTypes">
    <Type Name="ReportType">
      <Column Name="ReportTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="ReportType_Report" Member="Reports" ThisKey="ReportTypeID" OtherKey="ReportTypeID" Type="Report" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LogType_Log" Member="LogType" ThisKey="LogTypeID" OtherKey="LogTypeID" Type="LogType" IsForeignKey="true" />
      <Association Name="User_Log" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogTypes" Member="LogTypes">
    <Type Name="LogType">
      <Column Name="LogTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LogType" Member="LogType1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LogType_Log" Member="Logs" ThisKey="LogTypeID" OtherKey="LogTypeID" Type="Log" />
    </Type>
  </Table>
  <Table Name="dbo.StumpageModelPortfolioMultipliers" Member="StumpageModelPortfolioMultipliers">
    <Type Name="StumpageModelPortfolioMultiplier">
      <Column Name="StumpageModelPortfolioMultiplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StumpageGroupQualityCodeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HaulZone3Multiplier" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Column Name="HaulZone4Multiplier" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Column Name="HaulZone5Multiplier" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Association Name="StumpageGroupQualityCode_StumpageModelPortfolioMultiplier" Member="StumpageGroupQualityCode" ThisKey="StumpageGroupQualityCodeID" OtherKey="StumpageGroupQualityCodeID" Type="StumpageGroupQualityCode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WrongPasswordCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PasswordExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="User_StumpageModelPortfolio" Member="StumpageModelPortfolios" ThisKey="UserID" OtherKey="UserID" Type="StumpageModelPortfolio" />
      <Association Name="User_StumpageModelPortfolioShare" Member="StumpageModelPortfolioShares" ThisKey="UserID" OtherKey="UserID" Type="StumpageModelPortfolioShare" />
      <Association Name="User_Report" Member="Reports" ThisKey="UserID" OtherKey="UserID" Type="Report" />
      <Association Name="User_Log" Member="Logs" ThisKey="UserID" OtherKey="UserID" Type="Log" />
      <Association Name="User_MarketModelPortfolio" Member="MarketModelPortfolios" ThisKey="UserID" OtherKey="CreatedByUserID" Type="MarketModelPortfolio" />
      <Association Name="User_MarketModelPortfolio1" Member="MarketModelPortfolios1" ThisKey="UserID" OtherKey="UserID" Type="MarketModelPortfolio" />
      <Association Name="User_RPAPortfolio" Member="RPAPortfolios" ThisKey="UserID" OtherKey="CreatedByUserID" Type="RPAPortfolio" />
      <Association Name="User_RPAPortfolio1" Member="RPAPortfolios1" ThisKey="UserID" OtherKey="UserID" Type="RPAPortfolio" />
      <Association Name="UserStatuse_User" Member="UserStatuse" ThisKey="UserStatusID" OtherKey="UserStatusID" Type="UserStatuse" IsForeignKey="true" />
      <Association Name="UserType_User" Member="UserType" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MUKeys" Member="MUKeys">
    <Type Name="MUKey">
      <Column Name="MUKeyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MUKey" Member="MUKey1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MUSym" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FireDamageSusceptibility" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FireDamagePotential" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoilRuttingHazard" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuitabilityForRoadsNaturalSurface" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuitabilityForLogLandings" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConstructionLimitationsForHaulRoadsAndLogLandings" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HarvestEquipmentOperability" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MechanicalSitePreparationSurface" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MechanicalSitePreparationDeep" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuitabilityForHandPlanting" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuitabilityForMechanicalPlanting" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PotentialForSeedlingMortality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TreeSiteIndexDouglasFir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TreeSiteIndexWesternRedAlder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MUKey_MUKeyParcel" Member="MUKeyParcel" ThisKey="MUKeyID" OtherKey="MUKeyID" Type="MUKeyParcel" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.MUKeyParcels" Member="MUKeyParcels">
    <Type Name="MUKeyParcel">
      <Column Name="MUKeyParcelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MUKeyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Association Name="MUKey_MUKeyParcel" Member="MUKey" ThisKey="MUKeyID" OtherKey="MUKeyID" Type="MUKey" IsForeignKey="true" />
      <Association Name="Parcel_MUKeyParcel" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parcels" Member="Parcels">
    <Type Name="Parcel">
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelAllotment" Member="ParcelAllotments" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelAllotment" />
      <Association Name="Parcel_ParcelCounty" Member="ParcelCounties" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelCounty" />
      <Association Name="Parcel_ParcelEagle" Member="ParcelEagles" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelEagle" />
      <Association Name="Parcel_ParcelHaulZone" Member="ParcelHaulZones" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelHaulZone" />
      <Association Name="Parcel_ParcelLegal" Member="ParcelLegals" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelLegal" />
      <Association Name="Parcel_ParcelMurrelett" Member="ParcelMurreletts" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelMurrelett" />
      <Association Name="Parcel_ParcelOwl" Member="ParcelOwls" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelOwl" />
      <Association Name="Parcel_ParcelOwner" Member="ParcelOwners" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelOwner" />
      <Association Name="Parcel_ParcelRoadDistance" Member="ParcelRoadDistances" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelRoadDistance" Cardinality="One" />
      <Association Name="Parcel_ParcelRoadUseLength" Member="ParcelRoadUseLengths" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelRoadUseLength" Cardinality="One" />
      <Association Name="Parcel_ParcelStat" Member="ParcelStats" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelStat" Cardinality="One" />
      <Association Name="Parcel_ParcelZoning" Member="ParcelZonings" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelZoning" />
      <Association Name="Parcel_Report" Member="Reports" ThisKey="ParcelID" OtherKey="ParcelID" Type="Report" />
      <Association Name="Parcel_MUKeyParcel" Member="MUKeyParcels" ThisKey="ParcelID" OtherKey="ParcelID" Type="MUKeyParcel" />
      <Association Name="Parcel_ParcelRiparian" Member="ParcelRiparians" ThisKey="ParcelID" OtherKey="ParcelID" Type="ParcelRiparian" />
    </Type>
  </Table>
  <Table Name="dbo.RPAPortfolioDetails" Member="RPAPortfolioDetails">
    <Type Name="RPAPortfolioDetail">
      <Column Name="RPAPortfolioDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RPAPortfolioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogMarketReportSpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimberMarketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginningDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeginningRealValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="EndingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndingRealValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="RPA" Type="System.Decimal" DbType="Decimal(5,4) NOT NULL" CanBeNull="false" />
      <Column Name="Longevity" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Association Name="LogMarketReportSpecy_RPAPortfolioDetail" Member="LogMarketReportSpecy" ThisKey="LogMarketReportSpeciesID" OtherKey="LogMarketReportSpeciesID" Type="LogMarketReportSpecy" IsForeignKey="true" />
      <Association Name="TimberMarket_RPAPortfolioDetail" Member="TimberMarket" ThisKey="TimberMarketID" OtherKey="TimberMarketID" Type="TimberMarket" IsForeignKey="true" />
      <Association Name="RPAPortfolio_RPAPortfolioDetail" Member="RPAPortfolio" ThisKey="RPAPortfolioID" OtherKey="RPAPortfolioID" Type="RPAPortfolio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketModelPortfolios" Member="MarketModelPortfolios">
    <Type Name="MarketModelPortfolio">
      <Column Name="MarketModelPortfolioID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortfolioName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastEdited" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioCost" Member="MarketModelPortfolioCosts" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolioCost" Cardinality="One" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioDeliveredLogModelDetail" Member="MarketModelPortfolioDeliveredLogModelDetails" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolioDeliveredLogModelDetail" />
      <Association Name="MarketModelPortfolio_MarketModelPortfolioInflationDetail" Member="MarketModelPortfolioInflationDetails" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="MarketModelPortfolioInflationDetail" Cardinality="One" />
      <Association Name="MarketModelPortfolio_Report" Member="Reports" ThisKey="MarketModelPortfolioID" OtherKey="MarketModelPortfolioID" Type="Report" />
      <Association Name="User_MarketModelPortfolio" Member="User" ThisKey="CreatedByUserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_MarketModelPortfolio1" Member="User1" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RPAPortfolios" Member="RPAPortfolios">
    <Type Name="RPAPortfolio">
      <Column Name="RPAPortfolioID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortfolioName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastEdited" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="RPAPortfolio_RPAPortfolioDetail" Member="RPAPortfolioDetails" ThisKey="RPAPortfolioID" OtherKey="RPAPortfolioID" Type="RPAPortfolioDetail" />
      <Association Name="User_RPAPortfolio" Member="User" ThisKey="CreatedByUserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_RPAPortfolio1" Member="User1" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StandStats" Member="StandStats">
    <Type Name="StandStat">
      <Column Name="StandStatID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StandStat" Member="StandStat1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StandStat_ParcelRiparian" Member="ParcelRiparians" ThisKey="StandStatID" OtherKey="StandStatID" Type="ParcelRiparian" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelRiparians" Member="ParcelRiparians">
    <Type Name="ParcelRiparian">
      <Column Name="ParcelRiparianID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StandStatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acres" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Hectares" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Association Name="Parcel_ParcelRiparian" Member="Parcel" ThisKey="ParcelID" OtherKey="ParcelID" Type="Parcel" IsForeignKey="true" />
      <Association Name="StandStat_ParcelRiparian" Member="StandStat" ThisKey="StandStatID" OtherKey="StandStatID" Type="StandStat" IsForeignKey="true" />
      <Association Name="TimberCurrentStand_ParcelRiparian" Member="TimberCurrentStand" ThisKey="STD_ID" OtherKey="STD_ID" Type="TimberCurrentStand" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Scribner" Member="Scribner">
    <Type Name="Scribner">
      <Column Name="SED_IB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BoardFeet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length_ft" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetCurrentParcelTimberSummary" Method="GetCurrentParcelTimberSummary">
    <Parameter Name="parcelid" Type="System.Int32" DbType="Int" />
    <Parameter Name="reportyear" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCurrentParcelTimberSummaryResult">
      <Column Name="TotalBF" Type="System.Decimal" DbType="Decimal(38,19)" CanBeNull="true" />
      <Column Name="CommonName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SpeciesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>
